apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loadbalancerdrivers.lbcf.tkestack.io
spec:
  group: lbcf.tkestack.io
  names:
    kind: LoadBalancerDriver
    listKind: LoadBalancerDriverList
    plural: loadbalancerdrivers
    singular: loadbalancerdriver
    shortNames:
    - driver
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loadbalancers.lbcf.tkestack.io
spec:
  group: lbcf.tkestack.io
  names:
    kind: LoadBalancer
    listKind: LoadBalancerList
    plural: loadbalancers
    singular: loadbalancer
    shortNames:
    - lb
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backendgroups.lbcf.tkestack.io
spec:
  group: lbcf.tkestack.io
  names:
    kind: BackendGroup
    listKind: BackendGroupList
    plural: backendgroups
    singular: backendgroup
    shortNames:
    - bg
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backendrecords.lbcf.tkestack.io
spec:
  group: lbcf.tkestack.io
  names:
    kind: BackendRecord
    listKind: BackendRecordList
    plural: backendrecords
    singular: backendrecord
    shortNames:
    - br
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: binds.lbcf.tkestack.io
spec:
  group: lbcf.tkestack.io
  names:
    kind: Bind
    listKind: BindList
    plural: binds
    singular: bind
  scope: Namespaced
  subresources:
    status: {}
  version: v1
