/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "tkestack.io/lb-controlling-framework/pkg/apis/lbcf.tkestack.io/v1beta1"
	scheme "tkestack.io/lb-controlling-framework/pkg/client-go/clientset/versioned/scheme"
)

// BackendRecordsGetter has a method to return a BackendRecordInterface.
// A group's client should implement this interface.
type BackendRecordsGetter interface {
	BackendRecords(namespace string) BackendRecordInterface
}

// BackendRecordInterface has methods to work with BackendRecord resources.
type BackendRecordInterface interface {
	Create(*v1beta1.BackendRecord) (*v1beta1.BackendRecord, error)
	Update(*v1beta1.BackendRecord) (*v1beta1.BackendRecord, error)
	UpdateStatus(*v1beta1.BackendRecord) (*v1beta1.BackendRecord, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.BackendRecord, error)
	List(opts v1.ListOptions) (*v1beta1.BackendRecordList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackendRecord, err error)
	BackendRecordExpansion
}

// backendRecords implements BackendRecordInterface
type backendRecords struct {
	client rest.Interface
	ns     string
}

// newBackendRecords returns a BackendRecords
func newBackendRecords(c *LbcfV1beta1Client, namespace string) *backendRecords {
	return &backendRecords{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backendRecord, and returns the corresponding backendRecord object, and an error if there is any.
func (c *backendRecords) Get(name string, options v1.GetOptions) (result *v1beta1.BackendRecord, err error) {
	result = &v1beta1.BackendRecord{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backendrecords").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackendRecords that match those selectors.
func (c *backendRecords) List(opts v1.ListOptions) (result *v1beta1.BackendRecordList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.BackendRecordList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backendrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backendRecords.
func (c *backendRecords) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backendrecords").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a backendRecord and creates it.  Returns the server's representation of the backendRecord, and an error, if there is any.
func (c *backendRecords) Create(backendRecord *v1beta1.BackendRecord) (result *v1beta1.BackendRecord, err error) {
	result = &v1beta1.BackendRecord{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backendrecords").
		Body(backendRecord).
		Do().
		Into(result)
	return
}

// Update takes the representation of a backendRecord and updates it. Returns the server's representation of the backendRecord, and an error, if there is any.
func (c *backendRecords) Update(backendRecord *v1beta1.BackendRecord) (result *v1beta1.BackendRecord, err error) {
	result = &v1beta1.BackendRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backendrecords").
		Name(backendRecord.Name).
		Body(backendRecord).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *backendRecords) UpdateStatus(backendRecord *v1beta1.BackendRecord) (result *v1beta1.BackendRecord, err error) {
	result = &v1beta1.BackendRecord{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backendrecords").
		Name(backendRecord.Name).
		SubResource("status").
		Body(backendRecord).
		Do().
		Into(result)
	return
}

// Delete takes name of the backendRecord and deletes it. Returns an error if one occurs.
func (c *backendRecords) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backendrecords").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backendRecords) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backendrecords").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched backendRecord.
func (c *backendRecords) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackendRecord, err error) {
	result = &v1beta1.BackendRecord{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backendrecords").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
