/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "tkestack.io/lb-controlling-framework/pkg/apis/lbcf.tkestack.io/v1beta1"
)

// FakeBackendGroups implements BackendGroupInterface
type FakeBackendGroups struct {
	Fake *FakeLbcfV1beta1
	ns   string
}

var backendgroupsResource = schema.GroupVersionResource{Group: "lbcf.tkestack.io", Version: "v1beta1", Resource: "backendgroups"}

var backendgroupsKind = schema.GroupVersionKind{Group: "lbcf.tkestack.io", Version: "v1beta1", Kind: "BackendGroup"}

// Get takes name of the backendGroup, and returns the corresponding backendGroup object, and an error if there is any.
func (c *FakeBackendGroups) Get(name string, options v1.GetOptions) (result *v1beta1.BackendGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backendgroupsResource, c.ns, name), &v1beta1.BackendGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendGroup), err
}

// List takes label and field selectors, and returns the list of BackendGroups that match those selectors.
func (c *FakeBackendGroups) List(opts v1.ListOptions) (result *v1beta1.BackendGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backendgroupsResource, backendgroupsKind, c.ns, opts), &v1beta1.BackendGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BackendGroupList{ListMeta: obj.(*v1beta1.BackendGroupList).ListMeta}
	for _, item := range obj.(*v1beta1.BackendGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backendGroups.
func (c *FakeBackendGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backendgroupsResource, c.ns, opts))

}

// Create takes the representation of a backendGroup and creates it.  Returns the server's representation of the backendGroup, and an error, if there is any.
func (c *FakeBackendGroups) Create(backendGroup *v1beta1.BackendGroup) (result *v1beta1.BackendGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backendgroupsResource, c.ns, backendGroup), &v1beta1.BackendGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendGroup), err
}

// Update takes the representation of a backendGroup and updates it. Returns the server's representation of the backendGroup, and an error, if there is any.
func (c *FakeBackendGroups) Update(backendGroup *v1beta1.BackendGroup) (result *v1beta1.BackendGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backendgroupsResource, c.ns, backendGroup), &v1beta1.BackendGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackendGroups) UpdateStatus(backendGroup *v1beta1.BackendGroup) (*v1beta1.BackendGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backendgroupsResource, "status", c.ns, backendGroup), &v1beta1.BackendGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendGroup), err
}

// Delete takes name of the backendGroup and deletes it. Returns an error if one occurs.
func (c *FakeBackendGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backendgroupsResource, c.ns, name), &v1beta1.BackendGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackendGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backendgroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.BackendGroupList{})
	return err
}

// Patch applies the patch and returns the patched backendGroup.
func (c *FakeBackendGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackendGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backendgroupsResource, c.ns, name, data, subresources...), &v1beta1.BackendGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackendGroup), err
}
