/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "tkestack.io/lb-controlling-framework/pkg/apis/lbcf.tkestack.io/v1beta1"
)

// FakeLoadBalancers implements LoadBalancerInterface
type FakeLoadBalancers struct {
	Fake *FakeLbcfV1beta1
	ns   string
}

var loadbalancersResource = schema.GroupVersionResource{Group: "lbcf.tkestack.io", Version: "v1beta1", Resource: "loadbalancers"}

var loadbalancersKind = schema.GroupVersionKind{Group: "lbcf.tkestack.io", Version: "v1beta1", Kind: "LoadBalancer"}

// Get takes name of the loadBalancer, and returns the corresponding loadBalancer object, and an error if there is any.
func (c *FakeLoadBalancers) Get(name string, options v1.GetOptions) (result *v1beta1.LoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(loadbalancersResource, c.ns, name), &v1beta1.LoadBalancer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadBalancer), err
}

// List takes label and field selectors, and returns the list of LoadBalancers that match those selectors.
func (c *FakeLoadBalancers) List(opts v1.ListOptions) (result *v1beta1.LoadBalancerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(loadbalancersResource, loadbalancersKind, c.ns, opts), &v1beta1.LoadBalancerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.LoadBalancerList{ListMeta: obj.(*v1beta1.LoadBalancerList).ListMeta}
	for _, item := range obj.(*v1beta1.LoadBalancerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested loadBalancers.
func (c *FakeLoadBalancers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(loadbalancersResource, c.ns, opts))

}

// Create takes the representation of a loadBalancer and creates it.  Returns the server's representation of the loadBalancer, and an error, if there is any.
func (c *FakeLoadBalancers) Create(loadBalancer *v1beta1.LoadBalancer) (result *v1beta1.LoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(loadbalancersResource, c.ns, loadBalancer), &v1beta1.LoadBalancer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadBalancer), err
}

// Update takes the representation of a loadBalancer and updates it. Returns the server's representation of the loadBalancer, and an error, if there is any.
func (c *FakeLoadBalancers) Update(loadBalancer *v1beta1.LoadBalancer) (result *v1beta1.LoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(loadbalancersResource, c.ns, loadBalancer), &v1beta1.LoadBalancer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadBalancer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLoadBalancers) UpdateStatus(loadBalancer *v1beta1.LoadBalancer) (*v1beta1.LoadBalancer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(loadbalancersResource, "status", c.ns, loadBalancer), &v1beta1.LoadBalancer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadBalancer), err
}

// Delete takes name of the loadBalancer and deletes it. Returns an error if one occurs.
func (c *FakeLoadBalancers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(loadbalancersResource, c.ns, name), &v1beta1.LoadBalancer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLoadBalancers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(loadbalancersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.LoadBalancerList{})
	return err
}

// Patch applies the patch and returns the patched loadBalancer.
func (c *FakeLoadBalancers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.LoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(loadbalancersResource, c.ns, name, data, subresources...), &v1beta1.LoadBalancer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LoadBalancer), err
}
