/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BackendGroupListerExpansion allows custom methods to be added to
// BackendGroupLister.
type BackendGroupListerExpansion interface{}

// BackendGroupNamespaceListerExpansion allows custom methods to be added to
// BackendGroupNamespaceLister.
type BackendGroupNamespaceListerExpansion interface{}

// BackendRecordListerExpansion allows custom methods to be added to
// BackendRecordLister.
type BackendRecordListerExpansion interface{}

// BackendRecordNamespaceListerExpansion allows custom methods to be added to
// BackendRecordNamespaceLister.
type BackendRecordNamespaceListerExpansion interface{}

// LoadBalancerListerExpansion allows custom methods to be added to
// LoadBalancerLister.
type LoadBalancerListerExpansion interface{}

// LoadBalancerNamespaceListerExpansion allows custom methods to be added to
// LoadBalancerNamespaceLister.
type LoadBalancerNamespaceListerExpansion interface{}

// LoadBalancerDriverListerExpansion allows custom methods to be added to
// LoadBalancerDriverLister.
type LoadBalancerDriverListerExpansion interface{}

// LoadBalancerDriverNamespaceListerExpansion allows custom methods to be added to
// LoadBalancerDriverNamespaceLister.
type LoadBalancerDriverNamespaceListerExpansion interface{}
